[package]
edition = "2018"
name = "tangram_linear"
version = "0.0.0"

[lib]
path = "lib.rs"

[[bin]]
name = "boston-linear"
path = "benchmarks/boston.rs"

[[bin]]
name = "heart-disease-linear"
path = "benchmarks/heart-disease.rs"

[[bin]]
name = "iris-linear"
path = "benchmarks/iris.rs"

[dependencies]
itertools = "0.9"
ndarray = "0.13"
num-traits = "0.2"
rayon = "1.4"
super_unsafe = { path = "../super_unsafe" }
tangram_dataframe = { path = "../dataframe" }
tangram_metrics = { path = "../metrics" }
tangram_progress = { path = "../progress" }
tangram_thread_pool = { path = "../thread_pool" }
