[package]
name = "tangram_dataframe"
version = "1.0.0"
edition = "2018"

[lib]
path = "lib.rs"

[dev-dependencies]
insta = "0.16"

[dependencies]
anyhow = "1"
csv = "1"
itertools = "0.9"
lexical = "5"
ndarray = "0.13"
tangram_finite = { path = "../finite" }
