[package]
edition = "2018"
license = "MIT"
name = "tangram_dataframe"
version = "0.0.0"

[lib]
path = "lib.rs"

[dev-dependencies]
insta = "1"

[dependencies]
anyhow = "1"
csv = "1"
itertools = "0.9"
lexical = "5"
ndarray = "0.13"
num-traits = "0.2"
fnv = "1.0.7"
