[package]
name = "tangram-core"
version = "0.2.0-dev"
edition = "2018"

[lib]
path = "lib.rs"

[dev-dependencies]
insta = " 0.16"

[dependencies]
anyhow = "1"
buffy = { git = "https://github.com/tangram-hq/buffy" }
bytes = "0.5"
csv = "1"
derive_more = "0.99"
itertools = "0.9"
lexical = "5"
maplit = "1"
ndarray = { version = "0.13", features = ["rayon"] }
num-traits = "0.2"
once_cell = "1"
rand = "0.7"
rand_xoshiro = "0.4"
rayon = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.8"
thiserror = "1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wee_alloc = "0.4"
