[package]
name = "tangram-app"
version = "0.0.0"
edition = "2018"

[lib]
path = "lib.rs"

[dev-dependencies]
insta = "0.16"

[build-dependencies]
pinwheel = { path = "../pinwheel" }

[dependencies]
anyhow = "1"
base64 = "0.12"
bytes = "0.5"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = { version = "0.5", features = ["serde"] }
derive_more = "0.99"
dirs = "3"
futures = { version = "0.3" }
futures-util = { version = "0.3" }
hyper = { version = "0.13", features = ["stream"] }
include_dir = "0.6"
itertools = "0.9"
lexical = "5"
multer = "1.2"
ndarray = { version = "0.13", features = ["serde"] }
num-traits = "0.2"
pinwheel = { path = "../pinwheel" }
rand = "0.7"
reqwest = { version = "0.10", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.6"
sqlx = { git = "https://github.com/nitsky/sqlx", branch = "from_any_connect_options", default-features = false, features = ["any", "chrono", "postgres", "runtime-tokio", "sqlite"] }
tangram-core = { path = "../core" }
url = "2"
