[package]
edition = "2018"
license = "MIT"
name = "tangram_features"
version = "0.1.0-dev"

[lib]
path = "lib.rs"

[dependencies]
itertools = "0.9"
ndarray = "0.13"
num-traits = "0.2"
fnv = "1"
tangram_util = { path = "../util" }
tangram_dataframe = { path = "../dataframe" }
