[package]
edition = "2018"
license = "MIT"
name = "tangram_metrics"
version = "0.1.0-dev"

[lib]
path = "lib.rs"

[dev-dependencies]
insta = "1"

[dependencies]
itertools = "0.9"
ndarray = "0.14"
num-traits = "0.2"
tangram_util = { path = "../util" }
